# Generated by Django 3.0.5 on 2020-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20200405_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_ammount',
            field=models.BigIntegerField(default=0),
        ),
    ]
