# Generated by Django 3.0.2 on 2020-04-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField(auto_now_add=True)),
                ('is_currently_playing', models.BooleanField(default=False)),
                ('is_available_for_betting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('League', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcore.League')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('odd', models.IntegerField()),
                ('is_match_outcome', models.BooleanField(default=False)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='betcore.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='Mybet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField()),
                ('total_return', models.IntegerField()),
                ('is_won', models.BooleanField(default=False)),
                ('bets', models.ManyToManyField(to='betcore.Bet')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateBetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField()),
                ('total_return', models.CharField(max_length=10)),
                ('bet_code', models.IntegerField()),
                ('bets', models.ManyToManyField(to='betcore.Bet')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_teams', to='betcore.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='betcore.Team'),
        ),
    ]
