# Generated by Django 3.0.5 on 2020-04-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0002_auto_20200405_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatebetcode',
            name='total_return',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='league',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='betcore.Category'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='betcore.League'),
        ),
    ]
