# Generated by Django 3.0.5 on 2020-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0003_auto_20200405_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatebetcode',
            name='total_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
