# Generated by Django 3.0.5 on 2020-04-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0004_auto_20200407_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatebetcode',
            name='bet_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatebetcode',
            name='total_return',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
