# Generated by Django 3.0.5 on 2020-04-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0005_auto_20200407_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatebetcode',
            name='bet_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
