# Generated by Django 3.0.5 on 2020-04-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0007_mybet_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybet',
            name='bets',
            field=models.ManyToManyField(related_name='mybet_bets', to='betcore.Bet'),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='outcomes',
            field=models.ManyToManyField(related_name='mybet_outcomes', to='betcore.Outcome'),
        ),
    ]
