# Generated by Django 3.0.5 on 2020-04-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0008_auto_20200410_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatebetcode',
            name='stake',
        ),
        migrations.RemoveField(
            model_name='generatebetcode',
            name='total_return',
        ),
        migrations.AddField(
            model_name='generatebetcode',
            name='outcomes',
            field=models.ManyToManyField(related_name='bet_gen_outcomes', to='betcore.Outcome'),
        ),
    ]
