# Generated by Django 3.0.5 on 2020-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcore', '0009_auto_20200412_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatebetcode',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
