# Generated by Django 3.0.5 on 2020-04-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200404_1952'),
        ('users', '0002_auto_20200404_2046'),
    ]

    operations = [
    ]
